---
title: "7 Seconds or Less Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
# Course: Communicating Data
# Purpose: Provide an analysis on whether the 7 second offense is productive in improving overall win percentage in the NBA.
# Date: May 27, 2020
# Author: Joey Clancy

```

```{r clear-environment, echo = FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE))

# Clear environmet of packages
if (is.null(sessionInfo()$otherPkgs) == FALSE) lapply(paste("package:", names(sessionInfo()$otherPkgs), sep = ""), detach, character.only = TRUE, unload = TRUE)
```

```{r echo = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(patchwork)
library(plotly)
library(stringr)
library(RColorBrewer)
library(forcats)
library(flexdashboard)
```

```{r echo = FALSE, message = FALSE}
teamStat <- read.csv("teamStat.csv") # TEAM STATS
opponentStat <- read.csv("opponStat.csv") # Only used for join
winLoss <- read.csv("winLoss.csv") # Only used for join
```

```{r echo = FALSE, message = FALSE}
names(opponentStat)[names(opponentStat)=="PTS"] <- "PTS_ALLOWED"
names(teamStat)[names(teamStat)=="PTS"] <- "PTS_FOR"
```

```{r echo = FALSE, message = FALSE}
# Reorder data so that cbind function will work correctly
teamStat <- teamStat[order(teamStat$Team),]
opponentStat <- opponentStat[order(opponentStat$Team),]
winLoss <- winLoss[order(winLoss$Team),]

# Join the points allowed column to teamStat data
teamStat <- cbind(teamStat, PTS_ALLOWED = opponentStat$PTS_ALLOWED)
# Join Win and Losses column to teamStat data
teamStat <- cbind(teamStat, W = winLoss$W)
teamStat <- cbind(teamStat, L = winLoss$L)
teamStat <- cbind(teamStat, Pace = winLoss$Pace)

# Reorder by Wins
teamStat <- arrange(teamStat, -W)
```

```{r echo = FALSE, message = FALSE}
# Convert necessary variables to factors
teamStat$Team <- as.factor(teamStat$Team)
teamStat$Year <- as.factor(teamStat$Year)
```

```{r echo = FALSE, message = FALSE}
# Add Playoffs variable
teamStat$Playoffs = grepl("\\*", teamStat$Team)

# Add pythagorean expectation column
# Output is the EXPECTED win to loss ratio for each team (i.e. 0.75 = 75% win percentage)
teamStat$PYTHAG_WIN <- teamStat$PTS_FOR ^ 13.91 / (teamStat$PTS_FOR ^ 13.91 + teamStat$PTS_ALLOWED ^ 13.91)

# Add the ACTUAL win-loss ratio
teamStat$WIN_PERCENTAGE <- teamStat$W / (teamStat$W + teamStat$L)

# Add effective field goal percentage for teamStat
teamStat$eFG. <- (teamStat$FG + (0.5 * teamStat$X3P)) / teamStat$FGA

# Add 3PAr variable
teamStat$X3PAr <- teamStat$X3PA / teamStat$FGA
```

Column {data-width= 375}
-----------------------------------------------------------------------

### Suggestion 1: Shoot more threes

```{r echo = FALSE, message = FALSE}
memo1 <- teamStat %>% 
  group_by(Team) %>% 
  ggplot(mapping = aes(x = X3P., y = WIN_PERCENTAGE, color = Playoffs)) +
  geom_point(position = "jitter") +
  theme_classic() +
  scale_color_brewer(palette = "Set1") +
  theme(axis.ticks = element_blank(),
        axis.line.y = element_blank(),
        legend.position = "none") +
  labs(title = "Shooting 38% from three means a higher win percentage", subtitle = "And likely making the playoffs",x = "3P%", y = "Actual Win %") +
  annotate(geom = "rect", xmin = 0.38, xmax = 0.42, ymin = 0, ymax = 1, fill = "gray", alpha = 0.4) +
  annotate(geom = "text", x = 0.35, y = 0.905, label = "Blue denotes playoff teams")

memo1
```

### Suggestion 3: Play fast

```{r echo = FALSE, message = FALSE}
ggplotly(
  teamStat %>% 
    group_by(Year) %>% 
    summarize(medPace = median(Pace)) %>% 
    ggplot(mapping = aes(x = Year, y = medPace)) +
    geom_point() +
    labs(title = "A fast pace allows offenses to maximize scoring potential", x = "Year", y = "Pace") +
    theme_classic() +
    theme(axis.ticks.x = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank()) +
    annotate(geom = "rect", xmin = 8.5, xmax = 10.5, ymin = 90, ymax = 100.2, fill = "gray", alpha = 0.4) +
    annotate(geom = "text", x = 6, y = 98.3, label = "Largest increase from 2018 to 2019 (+3.1)")
)

```


Column {data-width=625}
-----------------------------------------------------------------------

### Suggestion 2: Shoot a maximum of 61 2P per game

```{r echo = FALSE, message = FALSE}
# Using plotly so that viewers can select specific two year ranges and clearly see the negative relationships that are present
ggplotly(
 teamStat %>% 
  mutate(Year = fct_recode(Year, `10-12` = "2010", `10-12` = "2011", `12-14` = "2012", `12-14` = "2013", `14-16` = "2014", `14-16` = "2015", `16-18` = "2016", `16-18` = "2017", `18-20` = "2018", `18-20` = "2019")) %>% 
  group_by(Team, Year) %>% 
  ggplot(mapping = aes(x = X2PA, y = WIN_PERCENTAGE, color = Year)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  theme_classic() +
  theme(axis.ticks.x = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "Beyond 5,000 2PA hurts win%", x = "Total 2P Attempted", y = "Win Percentage") +
  geom_vline(xintercept = 5000)
)
```

